### ISSUE TITLE
Can this be used for instrumentation?

### ISSUE THREAD

**Issue by mbebenita** [yurydelendik/wasmparser#6]
In other words, having both a streaming reader and a writer. I'm looking to instrument all memory reads / writes and this looks like the perfect place to start.

**Comment by yurydelendik** [comment]
Yes, it can. The 'Emitter' class was added in v2.0 at https://github.com/yurydelendik/wasmparser/blob/master/src/WasmEmitter.ts -- it can take input directly from the `BinaryReader` or its public functions can be called to construct a valid wasm file.

> I'm looking to instrument all memory reads / writes and this looks like the perfect place to start.

You probably will need to add additional import function (and type), which will trigger renumbering of all function indices in call,elem,export section/operators. But it's doable now. Closing as fixed.
