### ISSUE TITLE
streamable use case

### ISSUE THREAD

**Issue by drom** [yurydelendik/wasmparser#8]
@yurydelendik you mention that it is "streamable" parser. Could you provide and example of usage with the streams?

**Comment by yurydelendik** [comment]
This part is not ready yet, however here is blueprint:

```diff
diff --git a/disassemble-wasm.js b/disassemble-wasm.js
index 392ed73..60b677d 100644
--- a/disassemble-wasm.js
+++ b/disassemble-wasm.js
@@ -21,7 +21,36 @@ var fs = require('fs');
 var wasmPath = process.argv[2];
 var data = new Uint8Array(fs.readFileSync(wasmPath));
 
-var parser = new wasmparser.BinaryReader(data);
-parser.setData(data.buffer, 0, data.length);
+var parser = new wasmparser.BinaryReader();
 var dis = new wasmdis.WasmDisassembler();
+
+// buffer to hold pending data
+var buffer = new Uint8Array(1);
+var ensureBufferSize = function (size) {
+  if (buffer.byteLength >= size) return;
+  var newBuffer = new Uint8Array(size);
+  newBuffer.set(buffer);
+  buffer = newBuffer;
+};
+var pendingSize = 0;
+for (var i = 0; i < data.length;i++) {
+  var bufferSize = pendingSize + 1;
+  ensureBufferSize(bufferSize);
+  // Moving single byte from the input data
+  buffer[pendingSize] = data[i];
+
+  parser.setData(buffer.buffer, 0, bufferSize, false);
+  // Output will not be ready yet, parser.read() will be returning `null`.
+  // However dis's buffer has some data already.
+  var result = dis.disassemble(parser);
+  if (result !== null) throw new Error('assert: too early');
+
+  var pending = parser.data.subarray(parser.position, parser.length);
+  pendingSize = pending.length;
+  buffer.set(pending);
+}
+// Last chunk.
+parser.setData(buffer.buffer, 0, pendingSize, true);
+
 console.log(dis.disassemble(parser));
+console.log('Max buffer: ' + buffer.length);
diff --git a/src/WasmDis.ts b/src/WasmDis.ts
index e11248e..823b483 100644
--- a/src/WasmDis.ts
+++ b/src/WasmDis.ts
@@ -148,7 +148,7 @@ export class WasmDisassembler {
             case SectionCode.Function:
             case SectionCode.Code:
             case SectionCode.Memory:
-            case SectionCode.Data:
+            //case SectionCode.Data:
               break; // reading known section;
             default:
               reader.skipSection();
```

Try with `node disassemble-wasm.js test/spec.wasm`

Notice the Data section's contains init_expression, and readCodeOperator() must be more robust to cancel read for incomplete buffer.

**Comment by drom** [comment]
@yurydelendik how about making `getData()` API continuation passing style (CPS) async?

**Comment by yurydelendik** [comment]
For now I'll try to keep it low level, so any type of streams can use it, but for now buffer management and pulling data is managed by consumer. It's easy to adapt it to node.js streams, streams api.

> how about making getData() API continuation passing style (CPS) async?

Can you provide a complete API proposal?

**Comment by drom** [comment]
@yurydelendik yes, let me write something up.

**Comment by yurydelendik** [comment]
> you mention that it is "streamable" parser. Could you provide and example of usage with the streams?

Fixed multiple issues with reading incomplete buffer and added example at https://github.com/yurydelendik/wasmparser/blob/master/examples/print_imports_exports.js

>getOpcode(op =>
>   if (...) {
>      getVarint32(val =>

I don't think we want to dive that deep (I mean reading operand of operator) and I'm not sure how it will work for reading section->an_entry->init_export cases.

I'll close the issue since an example was created to address OP.
